image:
  file: .gitpod/.gitpod.Dockerfile

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - name: druxt.js
    before: git pull -f origin master:master
    init: |
      # druxt installation
      yarn install
      yarn build
      yarn build:docs
      gp sync-done bundle

  - name: drupal-9
    init: |
      # drupal installation
      .gitpod/download-ddev-images.sh
      .gitpod/setup-drupal.sh
      gp preview $(gp url 8080) --external
    command: |
      .gitpod/setup-ddev.sh
      cd $GITPOD_REPO_ROOT/examples/drupal/drupal-9 && ddev start
      gp preview $(gp url 8080) --external
      gp sync-done ddev

  - name: druxt-site
    init: |
      # druxt-site installation
      gp sync-await bundle
      cd $GITPOD_REPO_ROOT/examples/nuxt/druxt-site && yarn
    command: |
      gp sync-await ddev
      cd $GITPOD_REPO_ROOT/examples/nuxt/druxt-site && BASE_URL=$(gp url 8080) yarn dev

# VScode xdebug extension
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - editorconfig.editorconfig
    - felixfbecker.php-debug
    - gruntfuggly.todo-tree
    - octref.vetur

ports:
  # Nuxt/Druxt
  - port: 3000
    visibility: public
# Drupal
  - port: 8080
    visibility: public
# Currently un-notified and unsupported mailhog http port
  - port: 8025
    onOpen: ignore
# Currently un-notified and unsupported mailhog https port
  - port: 8026
    onOpen: ignore
# Currently un-notified and unsupported phpmyadmin http port
  - port: 8036
    onOpen: ignore
# Currently un-notified and unsupported phpmyadmin https port
  - port: 8037
    onOpen: ignore
# router http port that we're ignoring.
  - port: 8888
    onOpen: ignore
# router https port that we're ignoring.
  - port: 8889
    onOpen: ignore
# xdebug port
  - port: 9000
    onOpen: ignore
# projector port
  - port: 9999

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
    addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
